spring.datasource.url=jdbc:postgresql://localhost:5432/erp_lite_db
spring.datasource.username=postgres
spring.datasource.password=Koushikkmp@2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true